#
# Use this configuration file to control what RobotPy packages are installed
# on your SystemCore
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2027.0.0a2"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    # "all",
     "apriltag",
     "commands2",
    # "romi",
    # "sim",
    # "xrp",
]

# Other pip packages to install
requires = ["phoenix6==25.90.0a2","robotpy-rev==2027.0.0a1"]
